apiVersion: batch/v1
kind: CronJob
metadata:
  name: gtfs-warsaw
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: gtfs-warsaw
            image: public-transport/gtfs-warsaw:1.0.0
            imagePullPolicy: IfNotPresent
            env:
            - name: GTFS_ARGS
              value: "--metro"
          restartPolicy: OnFailure
