name: Deploy Docker Registry

on:
  workflow_dispatch:

env:
  DOCKER_TAG: public-transport/gtfs-warsaw
  DOCKER_VERSION: 1.0.0

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build docker
        run: docker build -t ${{ env.DOCKER_TAG }}:${{ env.DOCKER_VERSION }} .

      - name: Tag Image
        run: docker tag ${{ env.DOCKER_TAG }}:${{ env.DOCKER_VERSION }} ${{secrets.DOCKER_REGISTRY}}/${{ env.DOCKER_TAG }}:${{ env.DOCKER_VERSION }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200

